# Generated by Django 5.2 on 2025-04-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task', name='completed', ), migrations.AddField(
            model_name='task', name='status', field=models.CharField(
                choices=[
                    ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20), ), ]
