# Generated by Django 5.2 on 2025-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_completed_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
